# This is a basic workflow to help you get started with Actions
name: GitHub Actions

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-and-test"
  build-and-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: DeLaGuardo/setup-graalvm@4.0
      with:
        graalvm: '21.0.0.2'
        java: 'java11'
        arch: 'amd64'

    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@3.5
      with:
        # To use Clojure CLI 1.10.1.561 based on tools.deps
        cli: 1.10.3.943
        # leiningen and boot-cli can be installed as well
        lein: 2.9.6

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
